project:
  type: website
  output-dir: docs

website:
  title: "Lou Zhou"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - text: Resume
        href: assets/Lou_Zhou_Resume.pdf
        target: _blank

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    page-layout: full

editor: visual

